"""End-to-end smoke test of the common foundation (Step 10).

    python -m src.common.smoke_test            # development check
    python -m src.common.smoke_test --freeze   # freeze gate: stricter, must pass before tagging

What it does (on the REAL data in data/processed):
  1. data matches the committed split manifest
  2. dataset interface loads train/validation/test (+ length-controlled set)
  3. a RANDOM detector goes through schema -> evaluator and lands at chance
  4. the LENGTH-ONLY baseline (score = answer_length_chars) goes through the
     same path, with its threshold selected on validation and stored in the run
     meta; the report shows how much of its performance survives on the
     length-controlled set
  5. (--freeze) configuration is fully pinned / decided
  6. records git commit + config hash + manifest hash in
     results/foundation_smoke_report.json

Exit code 0 = no FAIL. WARN means "look at this", FAIL means "do not freeze".
The Llama GPU smoke test (load model, generate, extract hidden states) is
separate: run your Step 4-7 tests on a GPU machine as well.
"""
from __future__ import annotations

import argparse
import json
import subprocess
import sys
import time
from pathlib import Path

import numpy as np

REPO = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO))

from src.common import evaluator as E  # noqa: E402
from src.common.config import REPO_ROOT, SPLITS, get_config  # noqa: E402
from src.common.data import load_all, load_length_controlled  # noqa: E402
from src.common.schema import DetectorRecord, write_detector_output  # noqa: E402
from src.data import make_split_manifest as mm  # noqa: E402

CHECKS: list[dict] = []


def check(name: str, ok: bool, detail: str = "", *, warn_only: bool = False) -> bool:
    status = "PASS" if ok else ("WARN" if warn_only else "FAIL")
    CHECKS.append({"name": name, "status": status, "detail": detail})
    print(f"[{status}] {name}" + (f"  -  {detail}" if detail else ""))
    return ok


# Paths the smoke test (and the evaluator) write to; they must not make the tree "dirty".
GENERATED_PREFIXES = ("outputs/", "results/eval/", "results/foundation_smoke_report.json",
                      "results/env_report_")


def dirty_paths(porcelain: str) -> list[str]:
    """Paths from `git status --porcelain` that are NOT generated by the smoke test."""
    out = []
    for line in porcelain.splitlines():
        if len(line) < 4:
            continue
        path = line[3:]
        if " -> " in path:                      # rename
            path = path.split(" -> ", 1)[1]
        path = path.strip().strip('"').replace("\\", "/")
        if not path.startswith(GENERATED_PREFIXES):
            out.append(path)
    return out


def _git(*args) -> str | None:
    try:
        return subprocess.run(["git", *args], cwd=REPO_ROOT, capture_output=True, text=True,
                              timeout=20, check=True).stdout.rstrip()   # rstrip only: a leading space is meaningful in `git status --porcelain`
    except Exception:
        return None


def _records(samples, split, detector, variant, scores, cfg, latency_each):
    return [DetectorRecord(sample_id=s.sample_id, split=split, detector=detector, variant=variant,
                           score=float(sc), config_hash=cfg.config_hash(), prompt_version=cfg.prompt.version,
                           latency_s=latency_each, n_generations=0)
            for s, sc in zip(samples, scores)]


def _f(v):
    return "n/a" if v is None else f"{v:.4f}"


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--freeze", action="store_true", help="strict freeze gate")
    ap.add_argument("--seed", type=int, default=None, help="seed for the random detector (default: config seed)")
    args = ap.parse_args(argv)

    cfg = get_config()
    seed = cfg.run.seed if args.seed is None else args.seed
    print(f"config_hash={cfg.config_hash()}  prompt_version={cfg.prompt.version}  mode={'FREEZE' if args.freeze else 'dev'}\n")

    # 1. manifest ---------------------------------------------------------
    manifest_path = cfg.paths.resolve(cfg.paths.split_manifest)
    rc = mm.main(["verify"])
    check("data/processed matches split manifest", rc == 0)
    if rc != 0:
        print("\nCannot continue without verified data.")
        return _finish(cfg, args)

    # 2. dataset interface -------------------------------------------------
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    data = load_all()
    for s in SPLITS:
        exp = manifest["counts"][s]["samples"]
        check(f"load_split('{s}') count", len(data[s]) == exp, f"{len(data[s])} samples (manifest: {exp})")
        labs = [x.label for x in data[s]]
        check(f"{s}: balanced labels", labs.count(0) == labs.count(1), f"{labs.count(0)} factual / {labs.count(1)} hallucinated")

    ctrl = None
    try:
        ctrl = load_length_controlled()
        labs = [x.label for x in ctrl]
        check("length-controlled set loads and verifies", labs.count(0) == labs.count(1),
              f"{len(ctrl)} samples ({labs.count(0)}/{labs.count(1)})")
    except FileNotFoundError as e:
        check("length-controlled set present", False, str(e), warn_only=not args.freeze)

    val, test = data["validation"], data["test"]

    # 3. random detector ---------------------------------------------------
    rng = np.random.default_rng(seed)
    rv = _records(val, "validation", "smoke_random", f"seed{seed}", rng.random(len(val)), cfg, 0.0)
    rt = _records(test, "test", "smoke_random", f"seed{seed}", rng.random(len(test)), cfg, 0.0)
    thr_r = E.select_threshold(*E.align(val, E.records_to_scores(rv)), "youden")["value"]
    vp = write_detector_output(rv, threshold=thr_r, description="smoke test: random scores")
    tp = write_detector_output(rt, threshold=thr_r, description="smoke test: random scores")
    rep_r = E.evaluate_run(val_path=vp, test_path=tp, val_samples=val, test_samples=test,
                           ctrl_samples=ctrl, include_length_controlled=False)
    auc = rep_r["test"]["metrics"]["auroc"]
    pa = rep_r["test"]["pair_level"]["pair_accuracy"]
    check("random detector: test AUROC ~ 0.5", auc is not None and abs(auc - 0.5) < 0.05, f"AUROC={_f(auc)}")
    check("random detector: pair accuracy ~ 0.5", pa is not None and abs(pa - 0.5) < 0.06, f"pair_acc={_f(pa)}")

    # 4. length-only baseline ----------------------------------------------
    t0 = time.perf_counter()
    lv = [x.answer_length_chars for x in val]
    lt = [x.answer_length_chars for x in test]
    each = (time.perf_counter() - t0) / (len(val) + len(test))
    rv = _records(val, "validation", "length_only", "chars", lv, cfg, each)
    rt = _records(test, "test", "length_only", "chars", lt, cfg, each)
    thr = E.select_threshold(*E.align(val, E.records_to_scores(rv)), "youden")
    vp = write_detector_output(rv, threshold=thr["value"], description="length-only baseline (chars)")
    tp = write_detector_output(rt, threshold=thr["value"], description="length-only baseline (chars)")
    rep = E.evaluate_run(val_path=vp, test_path=tp, val_samples=val, test_samples=test,
                         ctrl_samples=ctrl, include_length_controlled=False, save=True)
    m = rep["test"]["metrics"]
    check("length-only: runs end-to-end through schema + evaluator", True,
          f"threshold={thr['value']:.1f} chars (validation, {thr['criterion']})")
    check("length-only: test AUROC > 0.5", m["auroc"] is not None and m["auroc"] > 0.5, f"AUROC={_f(m['auroc'])}")
    check("length-only: native pred_label agrees with evaluator rule",
          rep["test"]["metrics_native_pred_label"]["accuracy"] == m["accuracy"])

    print("\n--- length-only baseline (the confound check) ---")
    E.print_summary(rep)
    print("length-stratified (test):")
    for b in rep["test"]["length_stratified"]:
        if b["n"]:
            print(f"  {b['bin']:<14} n={b['n']:>4}  hallucinated={b['frac_hallucinated']:.2f}  "
                  f"acc={_f(b['accuracy'])}  AUROC={_f(b['auroc'])}")
    if ctrl is not None:
        cm = rep["length_controlled"]["metrics"]
        check("length-controlled set: length-only is evaluated", cm["n"] == len(ctrl),
              f"AUROC={_f(cm['auroc'])}, acc={_f(cm['accuracy'])}, "
              f"match_acc={_f(rep['length_controlled']['match_level']['match_accuracy'])}")
        # the controlled set exists precisely to neutralise length; if length-only still does well there, say so
        check("length-controlled set neutralises length (length-only AUROC < 0.65)",
              cm["auroc"] is not None and cm["auroc"] < 0.65, f"AUROC={_f(cm['auroc'])}", warn_only=True)

    # 5. configuration decisions -----------------------------------------------
    strict = args.freeze
    check("Llama revision pinned (config.model.revision)", cfg.model.revision is not None,
          str(cfg.model.revision), warn_only=not strict)
    check("prompt template frozen (config.prompt.version != 'v0-unfrozen')",
          cfg.prompt.version != "v0-unfrozen", cfg.prompt.version, warn_only=not strict)
    porcelain = _git("status", "--porcelain")
    dirty = None if porcelain is None else dirty_paths(porcelain)
    detail = "git not available" if dirty is None else (
        f"{len(dirty)} uncommitted: " + ", ".join(dirty[:5]) + (" ..." if len(dirty) > 5 else "") if dirty else "")
    check("git working tree clean (ignoring generated outputs/results)",
          dirty is not None and not dirty, detail, warn_only=not strict)

    return _finish(cfg, args, rep_length_only=rep)


def _finish(cfg, args, rep_length_only=None) -> int:
    n_fail = sum(c["status"] == "FAIL" for c in CHECKS)
    n_warn = sum(c["status"] == "WARN" for c in CHECKS)
    report = {
        "mode": "freeze" if args.freeze else "dev",
        "config_hash": cfg.config_hash(),
        "prompt_version": cfg.prompt.version,
        "git_commit": _git("rev-parse", "HEAD"),
        "git_branch": _git("rev-parse", "--abbrev-ref", "HEAD"),
        "manifest_sha256": None,
        "checks": CHECKS,
        "n_fail": n_fail, "n_warn": n_warn,
    }
    try:
        import hashlib
        mp = cfg.paths.resolve(cfg.paths.split_manifest)
        report["manifest_sha256"] = hashlib.sha256(mp.read_bytes().replace(b"\r\n", b"\n")).hexdigest()
    except Exception:
        pass
    if rep_length_only is not None:
        t = rep_length_only["test"]["metrics"]
        report["length_only_test"] = {"auroc": t["auroc"], "accuracy": t["accuracy"], "f1": t["f1"],
                                      "pair_accuracy": rep_length_only["test"]["pair_level"]["pair_accuracy"]}
        if "length_controlled" in rep_length_only:
            report["length_only_controlled"] = rep_length_only["length_controlled"]["metrics"]["auroc"]
    out = REPO_ROOT / cfg.paths.results_dir / "foundation_smoke_report.json"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(report, indent=2), encoding="utf-8")
    print(f"\n{len(CHECKS)} checks: {len(CHECKS) - n_fail - n_warn} PASS, {n_warn} WARN, {n_fail} FAIL   (report: {out})")
    if args.freeze and n_fail == 0:
        print("FREEZE GATE PASSED. Next: commit, then  git tag v0.1-foundation")
    elif n_fail:
        print("NOT READY: fix the FAIL items above.")
    return 1 if n_fail else 0


if __name__ == "__main__":
    sys.exit(main())
